mxRpc:
  #客户端配置消息
  client:
    debug: true
    #客户端ID标识
    id: 1011
    #提供的服务名称
    serviceName: ALL
    #访问权重 访问策略为权重方式下生效
    weight: 1
    #最长等待时间 单位s -1不限制
    maxWaitTime: 30
    #服务端连接参数
    link:
      #服务端IP
      host: 127.0.0.1
      #服务端端口
      port: 8082
      #服务端密码
      password: 123456789
  #服务端配置消息
  server:
    debug: true
    #监听端口号
    port: 8082
    #服务端密码
    password: 123456789
